# Generated by Django 3.0.8 on 2020-07-13 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_description', models.TextField(max_length=256)),
                ('job_start_date', models.DateField()),
                ('job_end_date', models.DateField()),
            ],
        ),
    ]
