# Generated by Django 3.0.8 on 2020-07-13 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0002_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_description', models.TextField()),
                ('award_start_date', models.DateField()),
                ('award_end_date', models.DateField()),
                ('award_institute', models.TextField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='experience',
            name='job_company',
            field=models.TextField(default='TESTING', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experience',
            name='job_description',
            field=models.TextField(),
        ),
    ]
