# Generated by Django 3.0.8 on 2020-07-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0003_auto_20200713_2157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='award_description',
            new_name='certificate_description',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='award_end_date',
            new_name='certificate_end_date',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='award_institute',
            new_name='certificate_institute',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='award_start_date',
            new_name='certificate_start_date',
        ),
        migrations.AddField(
            model_name='education',
            name='certificate_title',
            field=models.TextField(default='TTT', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experience',
            name='job_title',
            field=models.TextField(default='TTTTTT', max_length=256),
            preserve_default=False,
        ),
    ]
