# Generated by Django 3.0.8 on 2020-07-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0005_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interests_text', models.TextField()),
            ],
        ),
    ]
